# Generated by Django 6.0 on 2025-12-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ir', models.BigIntegerField()),
                ('red', models.BigIntegerField()),
                ('finger', models.BooleanField(default=False)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('pi', models.FloatField(blank=True, null=True)),
                ('rr', models.FloatField(blank=True, null=True)),
                ('sbp', models.IntegerField(blank=True, null=True)),
                ('dbp', models.IntegerField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
