# Generated by Django 6.0 on 2025-12-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='public_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
