# Generated by Django 6.0 on 2025-12-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsite', '0003_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
