# Generated by Django 6.0 on 2025-12-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsite', '0004_patient_archived_at_patient_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_esp32_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_esp32_url',
            field=models.URLField(blank=True),
        ),
    ]
